repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
- repo: git@github.com:coyainsurance/pre-commit-scalafmt.git
  rev: 1.0.1
  hooks:
  - id: scalafmt
    args: [ -t ] # pass `--test` to scalafmt; alternatively you can place here other supported cmdline arguments
